### ISSUE TITLE
请问下 config.json 的格式怎么写啊

### ISSUE THREAD

**Issue by zake1989** [CatchChat/Hydro.network#1]

**Comment by zake1989** [comment]
找到格式了  
 "server_auth": "/path",
  "can_do_invite": "/path",
  "do_invite": "/path",
  "validate_user": "/path"
这几个部分是什么啊

**Comment by kevinzhow** [comment]
我们验证用户用的
zake1989 notifications@github.com于2015年3月10日 周二上午10:55写道：
