### ISSUE TITLE
似乎从应用里面打开 VPN 和从 Notification Center 打开 VPN 要求的 profile 不一样？

### ISSUE THREAD

**Issue by bachue** [CatchChat/Hydro.network#4]
从应用中打开 VPN 需要安装 profile，然后在 Notification Center 中打开 VPN 又要求安装一个名字完全一样的 profile，为什么不是直接用之前安装好的那个？

**Comment by kevinzhow** [comment]
iOS 的限制

**Comment by bachue** [comment]
@kevinzhow 好吧 那是不是说从Notification Center里开启VPN App里是不知道的，因此没有显示已连接？

**Comment by kevinzhow** [comment]
可以让 App 里知道，但是不好保证同步性，所以干脆分开了。
但是平时你用Today里会远远多于App
