### ISSUE TITLE
能否作一个XXNet的IOS版本

### ISSUE THREAD

**Issue by xxnet** [CatchChat/Hydro.network#5]
看到你的开源，太棒了。

目前XXNet采用GAE，采用稳健的策略，不容易被封，即使有很多用户的时候。
能否开发一个IOS版本？

之前goagent-ios项目解决过一些问题，我们暂时联系不上原作者。
你能否开发一个类似的项目，造福大众？

有问题请跟我联系： xxnet.dev@gmail.com

**Comment by kevinzhow** [comment]
Hydro 是 IPSec 协议的，GAE 的 IP 被封的差不多了吧
xxnet notifications@github.com于2015年3月23日 周一上午10:46写道：

**Comment by xxnet** [comment]
IOS VPN似乎支持自定义VPN协议？
  好像加载一个模块到沙盒中运行，比如ShadowSocks的IOS实现？
  不了解，只是看过一些说法，特请教

GAE的IP还有很多短时间内不能封锁，就像Github不能简单封锁一样。
原版的 GoAgent难以使用，是因为它依赖DNS，XXNet的原理是自己扫描可用的Google ip，不依赖DNS服务，所以还可以使用，目前非常流畅、稳定。

欢迎交流。

**Comment by kevinzhow** [comment]
自定义协议严重受限
xxnet notifications@github.com于2015年3月23日 周一下午2:06写道：
